ERROR_CODE = {
    0: 'Success',
    1: 'User is not login',
    2: 'Success but find nothing',
    3: 'Duplicated Battle',
    4: 'Duplicated Battle but updated info',
    5: 'Not enough e Lements',
    100: 'System Error',
    101: 'Database find data error',
    102: 'Unknown Parameters',
    103: 'Signature not valid',
    104: 'CORS not valid',
    105: 'Server Error',
    106: 'User exist',
    107: 'User not exist',
    108: 'Password not match',
    109: 'DupLicated data',
    110: 'Game unit not found',
    111: 'No Pernission',
    112: ' Third party request error',
    113: 'Data is processing',
    114: 'Skill not found',
    115: 'Expired request',
    116: 'Contains sensitive word',
    117: 'Over 1imit',
    118: 'Pending request',
    129: 'Router not found',
    600: ' Unsupported region',
    601: 'IP blocked',
    429: 'Too many requests',
}
